### PR TITLE
Fix PrefixParser expected outcome

### PR DESCRIPTION
**Pull request by josephsnyder**
With the removal of GTM specific prefixes, update the expected output for
the PrefixParser test to include those new prefixes.

### CODE REVIEW

**Comment by shabiel** [comment]
Joe, can you tell me more about this?

**Comment by josephsnyder** [comment]
Sure! As part of https://github.com/OSEHRA/VistA/commit/3263484b30beb1309b17e090581404250d41f19f, we introduced two hard-coded removals of "GTM" and "gtm" as negative prefixes for the "Uncategorized" package.  For the test, we get the list of prefixes of the "Uncategorized" package and compare it to a known value which was not updated to include the GTM strings.

Dashboard result here: https://code.osehra.org/CDash/testDetails.php?test=3357517&build=44942

**Comment by whitten** [comment]
Since the Dashboard shows failure because it was expecting the gtm variants in the output list, does this mean that you modify the test results after you make the changes to code?

**Comment by josephsnyder** [comment]
Hi @whitten.  If I'm reading your question right, yes.  The test should have been updated when I made the code change but, unfortunately, I didn't.  I'll try and catch this next time.

**Pull request merged**
