### PR TITLE
SSH support for scripts generated by RASR

### PR DESCRIPTION
**Pull request by shabiel**

### CODE REVIEW

**Comment by ChristopherEdwards** [comment]
These changes look good to me

**Comment by josephsnyder** [comment]
Hi Sam, Thanks for the changes.  I was able to start the execution of the RAS tests on a Vagrant VM with these changes.  It showed some other issues, but they has nothing to do with this change.  

Now we have a slight issue in terms of procedure. Due to the two copies of VistA that are maintained, the updates for this repository should be sent through the OSEHRA Gerrit instance, http://review.code.osehra.org, so that both copies can be kept in sync automatically.

To make things worse, there is absolutely nothing saying that in the current repository, which is a fault on our side.  I had to go searching for this page to even find where we've mentioned it in the past: https://www.osehra.org/page/contributor-git-instructions

I've pushed this branch to Gerrit, the first commit of the branch is here http://review.code.osehra.org/#/c/707/1,  and will be approving and merging them from there.  I will also be generating a reStructuredText document to give the proper "how to contribute" instructions as part of the repository itself.  

Thanks again!

**Comment by shabiel** [comment]
Thank you Joe.

I will try to figure out how to use Gerrit next time. This is my first
contribution to the OSEHRA repository.

On Wed, Apr 20, 2016 at 7:26 AM, OSEHR Agent <notifications@github.com>
wrote:

> Merged #2 <https://github.com/OSEHRA/VistA/pull/2>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/OSEHRA/VistA/pull/2#event-634622352>
>



-- 
Sam Habiel, Pharm.D.
VISTA Expertise Network

**Comment by josephsnyder** [comment]
Its no trouble, Sam.  We are more than willing to work with people if they are willing to give us their updates.  The documentation commit is now in Gerrit, if you want to take a look:  http://review.code.osehra.org/#/c/710/

**Pull request merged**
